"""Tests for deterministic sentence segmentation.

The whole point of sentence-index extraction is that claim text is sliced from
the source rather than generated by an LLM. These tests defend the invariant that
every sentence's stored span slices back to its exact text, plus the boundary and
abbreviation rules that keep claims intact.
"""

from pathlib import Path

from truthfulness_evaluator.core.segmentation import Sentence, segment_sentences

FIXTURE = Path(__file__).parent / "fixtures" / "sample_project_doc.md"


class TestVerbatimInvariant:
    """document[s.start:s.end] == s.text must hold for every sentence."""

    def _assert_invariant(self, document: str) -> list[Sentence]:
        sentences = segment_sentences(document)
        for s in sentences:
            assert document[s.start : s.end] == s.text, f"span mismatch at index {s.index}"
        return sentences

    def test_simple_prose(self):
        doc = "Python was created in 1991. It is widely used today."
        sentences = self._assert_invariant(doc)
        assert [s.text for s in sentences] == [
            "Python was created in 1991.",
            "It is widely used today.",
        ]

    def test_terminator_variants(self):
        doc = "Is it fast? Yes! It really is."
        sentences = self._assert_invariant(doc)
        assert [s.text for s in sentences] == [
            "Is it fast?",
            "Yes!",
            "It really is.",
        ]

    def test_indices_are_contiguous(self):
        doc = "One fact here. Two facts here. Three facts here."
        sentences = self._assert_invariant(doc)
        assert [s.index for s in sentences] == [0, 1, 2]

    def test_markdown_document_invariant(self):
        doc = FIXTURE.read_text()
        self._assert_invariant(doc)


class TestAbbreviationHandling:
    """Abbreviations and numeric literals must not fragment a sentence."""

    def test_version_number_not_split(self):
        doc = "The API requires version 3.11 or higher."
        sentences = segment_sentences(doc)
        assert len(sentences) == 1
        assert sentences[0].text == doc

    def test_decimal_not_split(self):
        doc = "The threshold is 100.5 units for the test."
        sentences = segment_sentences(doc)
        assert len(sentences) == 1

    def test_common_abbreviations_not_split(self):
        doc = "See Dr. Smith, e.g. the 2021 study, for details."
        sentences = segment_sentences(doc)
        assert len(sentences) == 1
        assert sentences[0].text == doc

    def test_abbreviation_then_real_boundary(self):
        doc = "See Dr. Smith for details. The result was positive."
        sentences = segment_sentences(doc)
        assert [s.text for s in sentences] == [
            "See Dr. Smith for details.",
            "The result was positive.",
        ]

    def test_dotted_acronym_not_split(self):
        doc = "The U.S. government released the report in 2021."
        sentences = segment_sentences(doc)
        assert len(sentences) == 1
        assert sentences[0].text == doc


class TestStructuralBoundaries:
    """Headings, list items, and paragraphs are independent, selectable units."""

    def test_heading_is_own_sentence(self):
        doc = "# Title\n\nThe timeout is 60 seconds."
        sentences = segment_sentences(doc)
        assert sentences[0].text == "# Title"
        assert sentences[1].text == "The timeout is 60 seconds."

    def test_list_items_are_separate(self):
        doc = "Facts:\n\n- First claim here.\n- Second claim here.\n"
        texts = [s.text for s in segment_sentences(doc)]
        assert "- First claim here." in texts
        assert "- Second claim here." in texts

    def test_paragraph_break_splits(self):
        doc = "First paragraph claim\n\nSecond paragraph claim"
        texts = [s.text for s in segment_sentences(doc)]
        assert texts == ["First paragraph claim", "Second paragraph claim"]

    def test_ordered_list_marker_not_split_off(self):
        """An ordered-list marker stays attached to its item, no junk '1.'."""
        doc = "Steps:\n\n1. Install the package first.\n2. Run the setup script.\n"
        texts = [s.text for s in segment_sentences(doc)]
        assert "1. Install the package first." in texts
        assert "2. Run the setup script." in texts
        # The bare markers must never appear as their own sentences.
        assert "1." not in texts
        assert "2." not in texts


class TestEdgeCases:
    """Empty and whitespace-only inputs produce no sentences."""

    def test_empty_document(self):
        assert segment_sentences("") == []

    def test_whitespace_only(self):
        assert segment_sentences("   \n\n  \t ") == []

    def test_no_trailing_terminator(self):
        doc = "A claim with no ending punctuation"
        sentences = segment_sentences(doc)
        assert len(sentences) == 1
        assert sentences[0].text == doc

    def test_whitespace_excluded_from_span(self):
        doc = "  Leading and trailing spaces.  "
        sentences = segment_sentences(doc)
        assert sentences[0].text == "Leading and trailing spaces."
        assert doc[sentences[0].start : sentences[0].end] == sentences[0].text
